version: '3.8'

services:
  echopages:
    image: pachovit/echopages:latest
    # ports:
    #   - "8000:8000"
    environment:
      - TZ=Europe/Berlin
      - APP_EMAIL_ADDRESS=${APP_EMAIL_ADDRESS}
      - POSTMARK_SERVER_API_TOKEN=${POSTMARK_SERVER_API_TOKEN}
      - RECIPIENT_EMAIL=${RECIPIENT_EMAIL}
      - DELIVERY_SYSTEM=${DELIVERY_SYSTEM}
      - RECIPIENT_EMAIL=${RECIPIENT_EMAIL}
      - NUMBER_OF_UNITS_PER_DIGEST=${NUMBER_OF_UNITS_PER_DIGEST}
      - DAILY_TIME_OF_DIGEST=${DAILY_TIME_OF_DIGEST}
    volumes:
      - /echopages/data:/app/data
    restart: always
